# This is an empty configuraton file for Tabtype, which
# uses the Java properties sytax. See below for 
# an example of how to define a connection in this format.

#connections.derby.url=jdbc:derby:tabtype_user_derby;create=true
#connections.derby.username=tabtype
#connections.derby.password=PROMPT
#connections.derby.bg=#f0f0d7
#connections.derby.logBg=#a1a150
#connections.derby.logFg=#ffffff
#connections.derby.focusedBorderColor=#ee3838
#connections.derby.confirmations=true
#connections.derby.updatableResultSets=true
